---
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - haven=https://charts.goauthentik.io
check-version-increment: false
validate-maintainers: false
exclude-deprecated: true
excluded-charts: []